apiVersion: v1
kind: Namespace
metadata:
  name: east
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: east
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: quay.io/skupper/hello-world-backend
          ports:
            - containerPort: 8080
---
apiVersion: skupper.io/v2alpha1
kind: Site
metadata:
  name: east
  namespace: east
---
apiVersion: skupper.io/v2alpha1
kind: Connector
metadata:
  name: backend
  namespace: east
spec:
  routingKey: backend
  port: 8080
  selector: app=backend
